#ifndef RSSCONLINUX_H
#define RSSCONLINUX_H

#ifdef LINUX

#define RSSLINUX_ERROR_NOERROR 0
#define RSSLINUX_ERROR_OPENDEVICE -1
#define RSSLINUX_ERROR_CLOSEDEVICE -2
#define RSSLINUX_ERROR_SETUPDEVICE -3
#define RSSLINUX_ERROR_WRITE -4
#define RSSLINUX_ERROR_READ -5
#define RSSCON_BAUD_RATE B921600

#endif

#endif
